# See https://ezcv.readthedocs.io for documentation
name: Vanisri Kannan
theme: dimension
resume: true
email: vanisri.kannan@uts.edu.au
role: DevSecOps Intern
company: University of Technology Sydney
social:
  linkedin: vanisrikannan
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines
